apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ev-comments-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
