apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ev-auth-db-postgres
  name: ev-auth-db-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ev-auth-db-postgres
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ev-auth-db-postgres
    spec:
      containers:
      - args:
        - -p
        - "5433"
        env:
        - name: POSTGRES_DB
          value: evauthdb
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_USER
          value: admin
        image: postgres
        imagePullPolicy: ""
        name: ev-auth-db
        ports:
        - containerPort: 5433
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
