apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ev-ldap
  name: ev-ldap
spec:
  ports:
  - name: "389"
    port: 389
    targetPort: 389
  - name: "636"
    port: 636
    targetPort: 636
  selector:
    io.kompose.service: ev-ldap
status:
  loadBalancer: {}
