apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin-service
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30043
  selector:
    io.kompose.service: phpldapadmin
