apiVersion: v1
kind: Service
metadata:
  name: ev-users-ms-service-nodeport
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30543
  selector:
    role: users-db
