apiVersion: apps/v1
kind: Deployment
metadata:
  name: ev-wa
  labels:
    role: ev-wa
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: ev-wa
      tier: app
  template:
    metadata:
      labels:
        role: ev-wa
        tier: app
    spec:
      containers:
        - name: ev-wa
          image: jdiego55/ev-wa:2.3
          ports:
            - containerPort: 4000
