apiVersion: v1
kind: Service
metadata:
  name: ev-wa-service-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      name: http
  selector:
    role: ev-wa
    tier: app
