apiVersion: apps/v1
kind: Deployment
metadata:
  name: ev-proxy
  labels:
    role: ev-proxy
    tier: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      role: ev-proxy
      tier: proxy
  template:
    metadata:
      labels:
        role: ev-proxy
        tier: proxy
    spec:
      containers:
        - name: ev-proxy
          image: jdiego55/ev-proxy:0.1
          ports:
            - containerPort: 80
