apiVersion: apps/v1
kind: Deployment
metadata:
  name: ev-groups-ms
  labels:
    role: groups-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      role: groups-ms
      tier: ms
  template:
    metadata:
      labels:
        role: groups-ms
        tier: ms
    spec:
      containers:
        - name: ev-groups-ms
          image: gabothekiller/eventum-groups:0.2
          ports:
            - containerPort: 5001
