apiVersion: apps/v1
kind: Deployment
metadata:
  name: ev-apigateway
  labels:
    role: ev-api
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      role: ev-api
      tier: api
  template:
    metadata:
      labels:
        role: ev-api
        tier: api
    spec:
      containers:
        - name: ev-api
          image: gabothekiller/eventum-apigateway_ev-api:1.2
          ports:
            - containerPort: 5000
